---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes
- name: "install dependencies, such as NodeJS and NPM"
  become: yes
  apt:
    name: ["nodejs","npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    state: latest
    global: yes
    production: yes