---
- name: "copy artifact tar file to ec2 instance"
  copy:
    src: artifact.tar.gz
    dest: ~/
    backup: yes
- name: create a ~/udapeople directory
  file:
    path: ./udapeople
    state: directory

- name: extract archive
  ansible.builtin.unarchive:
    src: "~/artifact.tar.gz"
    dest: "~/udapeople"
    remote_src: true
    validate_certs: true

- name: install depndencies
  command: cd ~/udapeople && npm install
  args:
    chdir: ./udapeople 
      

- name: stop running pm2 services 
  command: pm2 stop default
  args:
    chdir: ./udapeople 
  
- name: start our application 
  command: pm2 start npm -- start
  args:
    chdir: ./udapeople 