---
- name: "copy artifact tar file to ec2 instance"
  copy:
    src: artifact.tar.gz
    dest: ~/
    backup: yes
- name: create a ~/udapeople directory
  file:
    path: ./udapeople
    state: directory

- name: extract archive
  ansible.builtin.unarchive:
    src: "~/artifact.tar.gz"
    dest: "~/udapeople"
    remote_src: true
    validate_certs: true

- name: install depndencies
  command: npm install
  args:
    chdir: ~/udapeople 

- name: build application
  command: npm run build
  args:
    chdir: ~/udapeople 
       
- name: start our application 
  command: pm2 start main.js  #pm2 start npm -- start
  args:
    chdir: ~/udapeople/dist 
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"